name: ci

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Checks
        run: docker compose run --rm checks
      - name: Docker Build
        run: docker compose build platform feed notifications audit
